// <auto-generated />
using System;
using AppConcurso.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppConcurso.Migrations
{
    [DbContext(typeof(ContextoBD))]
    [Migration("20250520132714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AppConcurso.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("DataNasc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("candidato");
                });

            modelBuilder.Entity("AppConcurso.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Edital")
                        .HasColumnType("longtext")
                        .HasColumnName("edital");

                    b.Property<string>("NomeCargo")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_cargo");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("salario_base");

                    b.HasKey("Id");

                    b.ToTable("cargo");
                });

            modelBuilder.Entity("AppConcurso.Models.Inscricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataInsc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inscricao");

                    b.Property<int>("IdCandidato")
                        .HasColumnType("int")
                        .HasColumnName("candidato_id");

                    b.Property<int>("IdCargo")
                        .HasColumnType("int")
                        .HasColumnName("cargo_id");

                    b.Property<decimal?>("NotaConhEspec")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("nota_conh_especificos");

                    b.Property<decimal?>("NotaConhGerais")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("nota_conh_gerais");

                    b.Property<int?>("NumInscricao")
                        .HasColumnType("int")
                        .HasColumnName("numero_insc");

                    b.HasKey("Id");

                    b.HasIndex("IdCandidato");

                    b.HasIndex("IdCargo");

                    b.ToTable("inscricao");
                });

            modelBuilder.Entity("AppConcurso.Models.Inscricao", b =>
                {
                    b.HasOne("AppConcurso.Models.Candidato", "Candidato")
                        .WithMany("Inscricoes")
                        .HasForeignKey("IdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppConcurso.Models.Cargo", "Cargo")
                        .WithMany("Inscricoes")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("AppConcurso.Models.Candidato", b =>
                {
                    b.Navigation("Inscricoes");
                });

            modelBuilder.Entity("AppConcurso.Models.Cargo", b =>
                {
                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
